volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    # restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    # restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
      - DOMAIN=${DOMAIN}
    # restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt_frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
    depends_on:
      - backend
    # restart: unless-stopped